"""empty message

Revision ID: 89f089b71c14
Revises: ae6cc5e497cd
Create Date: 2024-08-02 17:54:28.946334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f089b71c14'
down_revision = 'ae6cc5e497cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('address')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
